os: linux
dist: xenial

sudo: required

addons:
  apt:
    packages:
      - cpanminus
      - build-essential
      - libncurses5-dev
      - libpcre3-dev
      - libreadline-dev
      - libssl-dev
      - perl
      - etcd
      - luarocks
      # install golang environment
      - golang-go

cache:
  directories:
    - download-cache

env:
  global:
    - JOBS=2
    - OPENRESTY_PREFIX=/usr/local/openresty

install:
  - git clone https://github.com/openresty/test-nginx.git test-nginx
  - sudo luarocks install lua-resty-http
  - sudo luarocks install lua-typeof
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install openresty
  # run etcd local cluster, startup at localhost:2379, localhost:22379, and localhost:32379
  # see more https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/local_cluster.md
  - go get github.com/mattn/goreman

script:
  - cd test-nginx && (sudo cpanm --notest . > build.log 2>&1 || (cat build.log && exit 1)) && cd ..
  - export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
  - sudo service etcd start
  - goreman -f ./t/Procfile start > goreman.log 2>&1 &
  - make test jobs=$JOBS